from minStack import MinStack
from dynamicMinStack import DynamicMinStack


class CustomStack:
    def __init__(self):
        self.size = 5

    def minStack(self) -> None:
        obj = MinStack(self.size)
        print("IsEmpty: ", obj.isEmpty())
        print("IsFull: ", obj.isFull())
        print("Push 1: ", obj.push(1))
        print("Push 2: ", obj.push(2))
        print("Push 3: ", obj.push(3))
        print("Push 4: ", obj.push(4))
        print("Top: ", obj.getTop())
        print("Min: ", obj.getMin())
        print("Push 5: ", obj.push(5))
        print("IsEmpty: ", obj.isEmpty())
        print("IsFull: ", obj.isFull())
        print("Pop: ", obj.pop())
        print("Top: ", obj.getTop())
        print("Min: ", obj.getMin())
        print("Pop: ", obj.pop())
        print("Top: ", obj.getTop())
        print("Min: ", obj.getMin())
        print("Pop: ", obj.pop())
        print("Top: ", obj.getTop())
        print("Min: ", obj.getMin())
        print("Pop: ", obj.pop())
        print("Top: ", obj.getTop())
        print("Min: ", obj.getMin())
        print("IsEmpty: ", obj.isEmpty())
        print("IsFull: ", obj.isFull())
        print("Pop: ", obj.pop())
        print("Top: ", obj.getTop())
        print("Min: ", obj.getMin())
        print("IsEmpty: ", obj.isEmpty())
        print("IsFull: ", obj.isFull())

    def dynamicMinStack(self) -> None:
        obj = DynamicMinStack(self.size)
        print("IsEmpty: ", obj.isEmpty())
        print("IsFull: ", obj.isFull())
        print("Push 1: ", obj.push(1))
        print("Push 2: ", obj.push(2))
        print("Push 3: ", obj.push(3))
        print("Push 4: ", obj.push(4))
        print("Top: ", obj.getTop())
        print("Min: ", obj.getMin())
        print("Push 5: ", obj.push(5))
        print("IsEmpty: ", obj.isEmpty())
        print("IsFull: ", obj.isFull())
        print("Push 15: ", obj.push(15))
        print("IsEmpty: ", obj.isEmpty())
        print("IsFull: ", obj.isFull())
        print("Pop: ", obj.pop())
        print("Top: ", obj.getTop())
        print("Min: ", obj.getMin())
        print("Pop: ", obj.pop())
        print("Top: ", obj.getTop())
        print("Min: ", obj.getMin())
        print("Pop: ", obj.pop())
        print("Top: ", obj.getTop())
        print("Min: ", obj.getMin())
        print("Pop: ", obj.pop())
        print("Top: ", obj.getTop())
        print("Min: ", obj.getMin())
        print("IsEmpty: ", obj.isEmpty())
        print("IsFull: ", obj.isFull())
        print("Pop: ", obj.pop())
        print("Top: ", obj.getTop())
        print("Min: ", obj.getMin())
        print("IsEmpty: ", obj.isEmpty())
        print("IsFull: ", obj.isFull())


stack = CustomStack()
# stack.minStack()
stack.dynamicMinStack()
