from BasicQueue import BasicQueue
from CircularQueue import CircularQueue
from DynamicCircularQueue import DynamicCircularQueue


class Queue:
    def __init__(self):
        self.size = 5

    def basicQueue(self) -> None:
        basicQueue = BasicQueue(self.size)
        print("IsEmpty: ", basicQueue.isEmpty())
        print("Enqueue 1: ", basicQueue.enqueue(1))
        print("Enqueue 2: ", basicQueue.enqueue(2))
        print("Enqueue 3: ", basicQueue.enqueue(3))
        print("Enqueue 4: ", basicQueue.enqueue(4))
        print("Enqueue 5: ", basicQueue.enqueue(5))
        print("IsFull: ", basicQueue.isFull())
        print("Enqueue 15: ", basicQueue.enqueue(15))
        print("Rear: ", basicQueue.rear())
        print("Front: ", basicQueue.front())
        print("Dequeue: ", basicQueue.dequeue())
        print("Rear: ", basicQueue.rear())
        print("Front: ", basicQueue.front())
        print("IsEmpty: ", basicQueue.isEmpty())
        print("Dequeue: ", basicQueue.dequeue())
        print("Rear: ", basicQueue.rear())
        print("Front: ", basicQueue.front())
        print("IsEmpty: ", basicQueue.isEmpty())
        print("Dequeue: ", basicQueue.dequeue())
        print("Rear: ", basicQueue.rear())
        print("Front: ", basicQueue.front())
        print("IsEmpty: ", basicQueue.isEmpty())
        print("Dequeue: ", basicQueue.dequeue())
        print("Rear: ", basicQueue.rear())
        print("Front: ", basicQueue.front())
        print("IsEmpty: ", basicQueue.isEmpty())
        print("Dequeue: ", basicQueue.dequeue())
        print("Rear: ", basicQueue.rear())
        print("Front: ", basicQueue.front())
        print("IsEmpty: ", basicQueue.isEmpty())
        """
        This line would throw exception as in basic queue we can't enqueue more items once the queue becomes full, 
        even if we repeatedly dequeue.
        """
        print("Enqueue 15: ", basicQueue.enqueue(15))

    def circularQueue(self) -> None:
        circularQueue = DynamicCircularQueue(self.size)
        print("IsEmpty: ", circularQueue.isEmpty())
        print("Enqueue 1: ", circularQueue.enqueue(1))
        print("Enqueue 2: ", circularQueue.enqueue(2))
        print("Enqueue 3: ", circularQueue.enqueue(3))
        print("Enqueue 4: ", circularQueue.enqueue(4))
        print("Enqueue 5: ", circularQueue.enqueue(5))
        print("IsFull: ", circularQueue.isFull())
        print("Enqueue 15: ", circularQueue.enqueue(15))
        print("Rear: ", circularQueue.rear())
        print("Front: ", circularQueue.front())
        print("Dequeue: ", circularQueue.dequeue())
        print("Rear: ", circularQueue.rear())
        print("Front: ", circularQueue.front())
        print("IsEmpty: ", circularQueue.isEmpty())
        print("Dequeue: ", circularQueue.dequeue())
        print("Rear: ", circularQueue.rear())
        print("Front: ", circularQueue.front())
        print("IsEmpty: ", circularQueue.isEmpty())
        print("Dequeue: ", circularQueue.dequeue())
        print("Rear: ", circularQueue.rear())
        print("Front: ", circularQueue.front())
        print("IsEmpty: ", circularQueue.isEmpty())
        print("Dequeue: ", circularQueue.dequeue())
        print("Rear: ", circularQueue.rear())
        print("Front: ", circularQueue.front())
        print("IsEmpty: ", circularQueue.isEmpty())
        print("Dequeue: ", circularQueue.dequeue())
        print("Rear: ", circularQueue.rear())
        print("Front: ", circularQueue.front())
        print("IsEmpty: ", circularQueue.isEmpty())
        print("Enqueue 15: ", circularQueue.enqueue(15))
        print("Rear: ", circularQueue.rear())
        print("Front: ", circularQueue.front())
        print("IsFull: ", circularQueue.isFull())
        print("Enqueue 25: ", circularQueue.enqueue(25))
        print("Rear: ", circularQueue.rear())
        print("Front: ", circularQueue.front())
        print("IsFull: ", circularQueue.isFull())

    def dynamicCircularQueue(self) -> None:
        dynamicCircularQueue = DynamicCircularQueue(self.size)
        print("IsEmpty: ", dynamicCircularQueue.isEmpty())
        print("Enqueue 1: ", dynamicCircularQueue.enqueue(1))
        print("Enqueue 2: ", dynamicCircularQueue.enqueue(2))
        print("Enqueue 3: ", dynamicCircularQueue.enqueue(3))
        print("Enqueue 4: ", dynamicCircularQueue.enqueue(4))
        print("Enqueue 5: ", dynamicCircularQueue.enqueue(5))
        print("IsFull: ", dynamicCircularQueue.isFull())
        print("Enqueue 15: ", dynamicCircularQueue.enqueue(15))
        print("Rear: ", dynamicCircularQueue.rear())
        print("Front: ", dynamicCircularQueue.front())
        print("Dequeue: ", dynamicCircularQueue.dequeue())
        print("Rear: ", dynamicCircularQueue.rear())
        print("Front: ", dynamicCircularQueue.front())
        print("IsEmpty: ", dynamicCircularQueue.isEmpty())
        print("Dequeue: ", dynamicCircularQueue.dequeue())
        print("Rear: ", dynamicCircularQueue.rear())
        print("Front: ", dynamicCircularQueue.front())
        print("IsEmpty: ", dynamicCircularQueue.isEmpty())
        print("Dequeue: ", dynamicCircularQueue.dequeue())
        print("Rear: ", dynamicCircularQueue.rear())
        print("Front: ", dynamicCircularQueue.front())
        print("IsEmpty: ", dynamicCircularQueue.isEmpty())
        print("Dequeue: ", dynamicCircularQueue.dequeue())
        print("Rear: ", dynamicCircularQueue.rear())
        print("Front: ", dynamicCircularQueue.front())
        print("IsEmpty: ", dynamicCircularQueue.isEmpty())
        print("Dequeue: ", dynamicCircularQueue.dequeue())
        print("Rear: ", dynamicCircularQueue.rear())
        print("Front: ", dynamicCircularQueue.front())
        print("IsEmpty: ", dynamicCircularQueue.isEmpty())
        print("Enqueue 15: ", dynamicCircularQueue.enqueue(15))
        print("Rear: ", dynamicCircularQueue.rear())
        print("Front: ", dynamicCircularQueue.front())
        print("IsFull: ", dynamicCircularQueue.isFull())
        print("Enqueue 25: ", dynamicCircularQueue.enqueue(25))
        print("Rear: ", dynamicCircularQueue.rear())
        print("Front: ", dynamicCircularQueue.front())
        print("IsFull: ", dynamicCircularQueue.isFull())
        

queue = Queue()
# queue.basicQueue()
# queue.circularQueue()
queue.dynamicCircularQueue()
